// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xttuqwobpgresqropylq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh0dHVxd29icGdyZXNxcm9weWxxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMjk0NDksImV4cCI6MjA3MzcwNTQ0OX0.IFjoLUZksEY6TC8KSkbzWqdVOOPgipPcL6Ca5MNMISY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});